### PR TITLE
Add showcase section

### LINKED ISSUE #8: Banner showcase html of the web page
- [x]  Creates div element
- [x]  Uses a background image and h1 title

### LINKED ISSUE #9: the banner class for banner html

### PR DESCRIPTION
**Pull request by sabanyelkenci**
Hi group. Could you please review both HTML and CSS for the banner section? 
Thanks in advance

### CODE REVIEW

**Review by rago89 — APPROVED** [review]
Hi, I don't see errors :)

**Review by inggritenovaleta — APPROVED** [review]

**Comment by snicoll** [comment]
Rather than adding a merge commit to get the latest change from main (that's `Merge branch 'main' into showcase` in 
8ad8a9e), it would be better to rebase your commits instead. This doesn't add an unnecessary commit to this PR (there are two now while only one is necessary).

The merge commit is usually created when you "pull". To rebase instead, do the following while your are in the PR's branch (here `showcase`).

```
git fetch origin
git rebase origin/main
```

You're now on top of main with your commit. To push this to the remote (and update this PR) you need to "push force". The reason why you need to do that is because you've rewritten history (your initial commit wasn't at that place in time initially). you can do so as follows:

```
git push origin showcase --force
```

(the `--force` is key here). Keep in mind that rewriting history is fine for "personal branches", do not do this on a shared branch (especially on `main`) unless absolutely necessary.

There's no need to act on this PR but please keep this in mind going forward.

**Comment by rago89** [comment]
> Rather than adding a merge commit to get the latest change from main (that's `Merge branch 'main' into showcase` in
> [8ad8a9e](https://github.com/inggritenovaleta/hackyourfuture-g4/commit/8ad8a9e77e754e5f7efb131aac94c94457be45a3)), it would be better to rebase your commits instead. This doesn't add an unnecessary commit to this PR (there are two now while only one is necessary).
> 
> The merge commit is usually created when you "pull". To rebase instead, do the following while your are in the PR's branch (here `showcase`).
> 
> ```
> git fetch origin
> git rebase origin/main
> ```
> 
> You're now on top of main with your commit. To push this to the remote (and update this PR) you need to "push force". The reason why you need to do that is because you've rewritten history (your initial commit wasn't at that place in time initially). you can do so as follows:
> 
> ```
> git push origin showcase --force
> ```
> 
> (the `--force` is key here). Keep in mind that rewriting history is fine for "personal branches", do not do this on a shared branch (especially on `main`) unless absolutely necessary.
> 
> There's no need to act on this PR but please keep this in mind going forward.

Hi @snicoll the problem occurs because there were merging conflicts in the CSS file, the conflict was solved on GitHub by keeping both codes, and of course, Github requests a commit to save the changes.

**Comment by snicoll** [comment]
You shouldn't fix conflict on GitHub but on your machine.

**Pull request merged**
