### PR TITLE
Put logo image and modified btn 'Apply Now' in index.html

### PR DESCRIPTION
**Pull request by inggritenovaleta**
Instead of using URL, I put the logo Hack your future Belgium, stored in public/img folder. 
Also, I modified the href for 'btn'  Apply Now' from inside <ul> to <a> after </nav>.

### CODE REVIEW

**Comment by snicoll** [comment]
Nitpicking. 

What's the link with changing the log and changing the `Apply Now` link? These seems two totally different things that have no link with one another. Think of a PR as an increment that has a purpose (title). It's hard to give a meaningful description when something does two completely separate things. 

Going forward, please take that into account. Separating has the advantage of making review easier and reduce the likelihood of a conflict.

**Comment by inggritenovaleta** [comment]
I will take that into consideration (focus on one task for each PR). 
The image was input from @rago89  t have it stored in the img file, that is why I change it. 

regarding the 'Apply Button', I learned it from the previous assignment (Loruki Website) and easier to style.
However, is this okay to be merged or should I change something? 
Thank you in advance

**Comment by snicoll** [comment]
Sure, there's no need to move that to a different PR. As for the change itself, a member of the team should review the PR first I think.

**Comment by inggritenovaleta** [comment]
Thank you @snicoll

**Pull request merged**
