### PR TITLE
Add html and css for our program issues

### LINKED ISSUE #10: Our Program section html of the web page
- [x]  Creates div elements for the paragraph and image
- [x]  Uses h2, p and a elements

### LINKED ISSUE #11: the our-program class

### PR DESCRIPTION
**Pull request by sabanyelkenci**
It is okay in my local. Could you please review

### CODE REVIEW

**Review by rago89 — COMMENTED** [review]
I don't see any errors :), @sabanyelkenci  could you please take a look at the mergin conflicts and solve it

**Comment by snicoll** [comment]
The `our-program` branch is 9 commits behind which increases the likelihood of having a conflict. Rebasing frequently on top of `main` while coding is also a good idea to prevent this from happening. Again, from the `our-program` branch, assuming it was created of the `main` branch:

```
git fetch
git rebase origin/main
```

If you run this, your local copy will be in conflict resolution mode. Once you've fixed the conflict by editing the files, you can run `git rebase --continue` to continue rebasing your commits on top of `main`. Let me know how it goes.

**Comment by rago89** [comment]
> The `our-program` branch is 9 commits behind which increases the likelihood of having a conflict. Rebasing frequently on top of `main` while coding is also a good idea to prevent this from happening. Again, from the `our-program` branch, assuming it was created of the `main` branch:
> 
> ```
> git fetch
> git rebase origin/main
> ```
> 
> If you run this, your local copy will be in conflict resolution mode. Once you've fixed the conflict by editing the files, you can run `git rebase --continue` to continue rebasing your commits on top of `main`. Let me know how it goes.

is created from the showcase, in that case, I should rebase showcase and after that rebase main

**Comment by sabanyelkenci** [comment]
> The `our-program` branch is 9 commits behind which increases the likelihood of having a conflict. Rebasing frequently on top of `main` while coding is also a good idea to prevent this from happening. Again, from the `our-program` branch, assuming it was created of the `main` branch:
> 
> ```
> git fetch
> git rebase origin/main
> ```
> 
> If you run this, your local copy will be in conflict resolution mode. Once you've fixed the conflict by editing the files, you can run `git rebase --continue` to continue rebasing your commits on top of `main`. Let me know how it goes.

Hi @snicoll  
I did it right now and I am able to see the reasons that cause a conflict. Also, I changed some lines and the conflict is resolved right now. I have a question, do I need to make this control before pushing my changes or  anytime
Thank so much. This is a great tip for prevent conflicts

**Comment by sabanyelkenci** [comment]
> > The `our-program` branch is 9 commits behind which increases the likelihood of having a conflict. Rebasing frequently on top of `main` while coding is also a good idea to prevent this from happening. Again, from the `our-program` branch, assuming it was created of the `main` branch:
> > ```
> > git fetch
> > git rebase origin/main
> > ```
> > 
> > 
> > If you run this, your local copy will be in conflict resolution mode. Once you've fixed the conflict by editing the files, you can run `git rebase --continue` to continue rebasing your commits on top of `main`. Let me know how it goes.
> 
> is created from the showcase, in that case, I should rebase showcase and after that rebase main
> 

Hi @rago89. I understood I have to open a branch from the main branch. I couldn't aware of it while I create the our-program branch. Is that reason why I can not see my changes for our program in the main branch or after submitting the review can I see all the changes together?
thanks in advance

**Comment by snicoll** [comment]
Yes rebasing before submitting is a good idea. And having two branches may not be the easiest here. Try to keep on top of main only.

**Review by rago89 — COMMENTED** [review]
I don't see errors, code is matching with the HYF page

**Pull request merged**
